stages:
- build
- test

before_script:
- apk update
- apk add bash

build:
  image: ruby:alpine
  stage: build
  script:
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - dist/
  tags:
  - Docker

test:
  image: nginx:alpine
  stage: test
  dependencies:
  - build
  script:
  - apk add openssl
  - ./test.sh
  artifacts:
    paths:
    - dist/
  tags:
  - Docker
