stages:
- build
- test

build:
  image: ruby:alpine
  stage: build
  script:
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - dist/
  tags:
  - Docker

test:
  image: nginx:alpine
  stage: test
  script:
  # - apk update
  # - apk add bash
  - ./test.sh
  artifacts:
    paths:
    - dist/
  tags:
  - Docker
