stages:
- build
- test
- deploy

before_script:
- apk update
- apk add bash

build:
  image: ruby:alpine
  stage: build
  script:
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - dist/
  tags:
  - docker

test:
  image: nginx:alpine
  stage: test
  dependencies:
  - build
  script:
  - apk add openssl
  - ./test.sh
  artifacts:
    paths:
    - dist/
  tags:
  - docker

deploy:
  stage: deploy
  dependencies:
  - build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  script:
    - mv dist/sites-available dist/sites-enabled
    - docker build -t registry.dbogatov.org/dbogatov/nginx-config .
    - docker push registry.dbogatov.org/dbogatov/nginx-config
  tags:
  - shell
